package com.ecvs.overrideload.dto;

import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * Request body for POST /api/v1/override-load.
 * batchId is generated by /api/v1/override-extract.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OverrideLoadRequest {

    @NotNull(message = "batchId is required")
    private UUID batchId;
}
